blank_issues_enabled: true
contact_links:
  - name: 💬 Preguntas y Discusiones
    url: https://github.com/LucaGMB/al-mazo/discussions
    about: Usa las discusiones comunitarias para preguntas generales o soporte no relacionado a bugs.
