import type { CardTemplate } from './engine.js';

export const HDP_DECK_PROMPTS: Array<{ text: string; picks?: number }> = [
  { text: 'En el cumpleaños de mi abuela no puede faltar ___.' },
  { text: 'El nuevo plan económico incluye ___ para todos.' },
  { text: 'Lo que más me gusta del verano es ___.' },
  { text: 'Mi terapeuta dice que tengo que dejar de pensar en ___.' },
  { text: 'El ingrediente secreto del asado de mi tío es ___.' },
  { text: 'En la reunión familiar siempre termina apareciendo ___.' },
  { text: 'La verdadera razón por la que falté al trabajo fue ___.' },
  { text: 'El nuevo servicio de streaming se llama "___{___}".', picks: 2 },
  { text: 'Nunca pensé que diría esto, pero ___ me salvó la vida.' },
  { text: 'En el noticiero de las 20 hablaron de ___ durante 40 minutos.' },
  { text: 'Mi grupo de amigos se separó por culpa de ___.' },
  { text: 'Lo que el país necesita para salir adelante es ___.' },
  { text: 'El menú del restaurante más caro es ___ con ___.', picks: 2 },
  { text: 'La fórmula secreta de la felicidad es ___ y ___.', picks: 2 },
  { text: 'Cuando llegue la inteligencia artificial, seremos reemplazados por ___.' },
  { text: 'El regalo perfecto para el Día del Amigo es ___.' },
  { text: 'En la isla desierta solo me llevaría ___ y ___.', picks: 2 },
  { text: 'La serie documental de la semana se llama "El misterio de ___".' },
  { text: 'Mi rutina de ejercicios consiste en ___ tres veces por semana.' },
  { text: 'El verdadero motivo de la guerra fue ___.' },
  { text: 'La receta de la abuela lleva ___, ___ y mucho amor.', picks: 3 },
  { text: 'Para ser feliz necesitás ___, ___ y ___.', picks: 3 },
];

export const HDP_DECK_ANSWERS: Array<{ text: string; articleOptional?: boolean }> = [
  { text: 'Un mate lavado', articleOptional: true },
  { text: 'El loro de la vecina', articleOptional: true },
  { text: 'Una empanada de carne con pasas', articleOptional: true },
  { text: 'Un fernet con coca a las 11 de la mañana', articleOptional: true },
  { text: 'La inflación', articleOptional: true },
  { text: 'Un perro con sombrero', articleOptional: true },
  { text: 'El más zarpado del barrio', articleOptional: true },
  { text: 'Una siesta de cuatro horas', articleOptional: true },
  { text: 'Un cover de Los Palmeras', articleOptional: true },
  { text: 'La prima del primo', articleOptional: true },
  { text: 'Un karaoke roto', articleOptional: true },
  { text: 'Mi jefe bailando cumbia' },
  { text: 'Un asado sin carbón', articleOptional: true },
  { text: 'La vieja confiable', articleOptional: true },
  { text: 'Un gato con planes malvados', articleOptional: true },
  { text: 'El último alfajor de la caja', articleOptional: true },
  { text: 'Una fila del banco un lunes', articleOptional: true },
  { text: 'El grupo de WhatsApp de la familia', articleOptional: true },
  { text: 'Un pato que no aprende a nadar', articleOptional: true },
  { text: 'La abuela con el control remoto', articleOptional: true },
  { text: 'Dormir con la tele prendida' },
  { text: 'Un vuelto en monedas', articleOptional: true },
  { text: 'El amigo que nunca paga', articleOptional: true },
  { text: 'Un cartel que dice "no pasar"', articleOptional: true },
  { text: 'La emoción de terminar la serie', articleOptional: true },
  { text: 'Un plan de ahorro en cuotas', articleOptional: true },
  { text: 'El wifi del vecino', articleOptional: true },
  { text: 'Una ola de calor', articleOptional: true },
  { text: 'El tío que cuenta chistes malos', articleOptional: true },
  { text: 'Un birra caliente', articleOptional: true },
  { text: 'La respuesta correcta en un examen que no estudiaste', articleOptional: true },
  { text: 'Un gato atrapado en un árbol', articleOptional: true },
  { text: 'El ruido del secador de pelo a la madrugada', articleOptional: true },
  { text: 'Una discusión por el asiento del auto', articleOptional: true },
  { text: 'El vecino que taladra los domingos', articleOptional: true },
  { text: 'Un documento en PDF de 200 páginas', articleOptional: true },
  { text: 'El último pedazo de pizza', articleOptional: true },
  { text: 'Una reunión que pudo haber sido un mail', articleOptional: true },
  { text: 'Un chiste que solo yo entiendo', articleOptional: true },
  { text: 'La bufanda que teje mi abuela', articleOptional: true },
  { text: 'Un viernes a las 18:59', articleOptional: true },
  { text: 'El silencio incómodo en el ascensor', articleOptional: true },
  { text: 'Una gallina con actitud', articleOptional: true },
  { text: 'El pan del día anterior', articleOptional: true },
  { text: 'Un aplauso en el micro', articleOptional: true },
  { text: 'La lista de compras olvidada en la heladera', articleOptional: true },
  { text: 'Mi historial de búsqueda' },
  { text: 'Un control remoto sin pilas', articleOptional: true },
  { text: 'La primera mañana de vacaciones', articleOptional: true },
  { text: 'Un perro que cree ser humano', articleOptional: true },
  { text: 'El mate del compañero de trabajo', articleOptional: true },
  { text: 'Una siesta interrumpida por el timbre', articleOptional: true },
  { text: 'Un kiosco de barrio a las 3 AM', articleOptional: true },
  { text: 'La costumbre de decir "ya fue"', articleOptional: true },
  { text: 'Un cumpleaños sin torta', articleOptional: true },
  { text: 'El ruido de la lluvia en el techo de chapa', articleOptional: true },
  { text: 'Una idea genial a las 4 de la mañana', articleOptional: true },
  { text: 'El manual de instrucciones en otro idioma', articleOptional: true },
  { text: 'Un partido definido por un penal dudoso', articleOptional: true },
  { text: 'La última galletita de la olla', articleOptional: true },
  { text: 'Un aula vacía un viernes', articleOptional: true },
  { text: 'El portero que sabe todo', articleOptional: true },
  { text: 'Una promesa de campaña', articleOptional: true },
  { text: 'El olor a café de la oficina', articleOptional: true },
  { text: 'Un invierno sin calefacción', articleOptional: true },
  { text: 'La playlist de un casamiento', articleOptional: true },
  { text: 'Un mensaje sin responder desde hace tres semanas', articleOptional: true },
  { text: 'El campeón del barrio', articleOptional: true },
  { text: 'Una abuela que juega al póker', articleOptional: true },
  { text: 'El ruido de la máquina de coser', articleOptional: true },
  { text: 'Un colectivo que nunca llega', articleOptional: true },
  { text: 'La comida del avión', articleOptional: true },
  { text: 'Un paraguas roto', articleOptional: true },
  { text: 'El perro del vecino ladrando a la luna', articleOptional: true },
  { text: 'Una soda bien fría', articleOptional: true },
  { text: 'El sabor de una derrota', articleOptional: true },
  { text: 'Un lunes sin café', articleOptional: true },
  { text: 'La letra chica de un contrato', articleOptional: true },
  { text: 'Un vecino que cree que sabe cantar', articleOptional: true },
  { text: 'El aplauso después del apagón', articleOptional: true },
  { text: 'Un chiste repetido mil veces', articleOptional: true },
  { text: 'El ruido de la moto a las 3 AM', articleOptional: true },
  { text: 'Una fila de trámites', articleOptional: true },
  { text: 'El perro que se come los deberes', articleOptional: true },
  { text: 'Una vieja discutiendo el precio', articleOptional: true },
  { text: 'Un mosquito en la pieza', articleOptional: true },
  { text: 'La última empanada de la bandeja', articleOptional: true },
  { text: 'Un profe que no explica nada', articleOptional: true },
  { text: 'El domingo a la tardecita', articleOptional: true },
  { text: 'El olor a lluvia en el campo', articleOptional: true },
];

export function buildHdpDeckTemplates(): CardTemplate[] {
  const templates: CardTemplate[] = HDP_DECK_PROMPTS.map((prompt) => ({
    count: 1,
    type: 'PROMPT',
    metadata: { text: prompt.text, picks: prompt.picks ?? 1 },
  }));

  for (const answer of HDP_DECK_ANSWERS) {
    templates.push({
      count: 1,
      type: 'ANSWER',
      metadata: { text: answer.text, articleOptional: Boolean(answer.articleOptional) },
    });
  }
  return templates;
}
