export const NAME_MODIFIERS = [
  'Turbo',
  'Mega',
  'Mini',
  'Súper',
  'Pixel',
  'Neón',
  'Ciber',
  'Retro',
  'Cometa',
  'Trueno',
  'Rayo',
  'Chispa',
  'Tornado',
  'Galaxia',
  'Leyenda',
  'Little',
  'Crazy',
  'Tiny',
  'Mighty',
  'Golden',
  'Shadow',
  'Lucky',
  'Wild',
  'Quantum',
];

export const NAME_FIGURES = [
  'Torvalds',
  'Turing',
  'Curie',
  'Einstein',
  'Newton',
  'Tesla',
  'Darwin',
  'Galileo',
  'Lovelace',
  'Hopper',
  'Hawking',
  'Edison',
  'Sagan',
  'Mozart',
  'Beethoven',
  'Lennon',
  'Bowie',
  'Mercury',
  'Kahlo',
  'Picasso',
  'Dalí',
  'Warhol',
  'Borges',
  'Cortázar',
  'Neruda',
  'Messi',
  'Maradona',
  'Pelé',
  'Fangio',
  'Nadal',
  'Jordan',
  'Bolt',
  'Chaplin',
  'Kubrick',
  'Miyazaki',
];

export function randomPlayerName(rng: () => number = Math.random): string {
  const modifier = NAME_MODIFIERS[Math.floor(rng() * NAME_MODIFIERS.length)];
  const figure = NAME_FIGURES[Math.floor(rng() * NAME_FIGURES.length)];
  return `${modifier} ${figure}`;
}
